# Generated by Django 5.0.4 on 2024-05-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('date_achat', models.DateField()),
                ('image', models.ImageField(upload_to='voitures/')),
                ('puissance_fiscale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_carburant', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electrique', 'Électrique')], max_length=50)),
                ('boite_vitesse', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=50)),
                ('model', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=100)),
                ('montant_achat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_assurance', models.CharField(max_length=100)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.voiture')),
            ],
        ),
    ]
