# Generated by Django 5.0.4 on 2024-05-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='prix',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
