# Generated by Django 5.0.4 on 2024-05-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_voiture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='statut_mecanique',
            field=models.CharField(choices=[('Bon état', 'Bon état'), ('Besoin de réparations mineures', 'Besoin de réparations mineures'), ('Besoin de réparations majeures', 'Besoin de réparations majeures')], default='Bon état', max_length=50),
        ),
    ]
