# Generated by Django 5.0.4 on 2024-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_voiture_statut_mecanique'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
