# Generated by Django 5.0.4 on 2024-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_voiture_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='available',
        ),
        migrations.AddField(
            model_name='voiture',
            name='disponibilite',
            field=models.CharField(default='oui', max_length=5),
        ),
    ]
