# Generated by Django 5.0.4 on 2024-05-31 09:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
