# Generated by Django 5.0.4 on 2024-05-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0004_voiture_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('naissance', models.DateField()),
                ('permit', models.CharField(max_length=20)),
                ('delevrence', models.DateField()),
                ('email', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=50)),
                ('adresse2', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('image_permit', models.ImageField(upload_to='permit/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Commande_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_encharge', models.DateField()),
                ('date_endepot', models.DateField()),
                ('disponibilite', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.client')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.voiture')),
            ],
        ),
    ]
