# Generated by Django 5.0.4 on 2024-05-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_commande_reservation_matricule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_reservation',
            name='voiture',
        ),
    ]
