# Generated by Django 5.0.4 on 2024-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_commande_reservation_voiture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image_permit',
        ),
        migrations.AddField(
            model_name='commande_reservation',
            name='image_permit',
            field=models.ImageField(default='true', upload_to='permit/%y/%m/%d'),
        ),
    ]
