# Generated by Django 5.0.4 on 2024-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_client_image_permit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='client',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='user/%y/%m/%d'),
        ),
    ]
