# Generated by Django 5.0.4 on 2024-05-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_reservation',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
