# Generated by Django 5.0.4 on 2024-05-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
