# Generated by Django 5.0.4 on 2024-05-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('administration', '0004_voiture_available'),
        ('index', '0009_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_reservation',
            name='client',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.PROTECT, to='account.client'),
        ),
        migrations.AddField(
            model_name='commande_reservation',
            name='voiture',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.PROTECT, to='administration.voiture'),
        ),
    ]
