# Generated by Django 5.0.4 on 2024-05-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('administration', '0005_remove_voiture_available_voiture_disponibilite'),
        ('index', '0012_alter_commande_reservation_image_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_reservation',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.client'),
        ),
        migrations.AlterField(
            model_name='commande_reservation',
            name='image_permit',
            field=models.ImageField(blank=True, null=True, upload_to='permit/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='commande_reservation',
            name='totalprix',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='commande_reservation',
            name='voiture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.voiture'),
        ),
    ]
