# Generated by Django 5.0.4 on 2024-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_commande_reservation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_reservation',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
