# Generated by Django 5.0.4 on 2024-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_commande_reservation_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_reservation',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
