# Generated by Django 5.0.4 on 2024-05-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_client_phone'),
        ('administration', '0005_remove_voiture_available_voiture_disponibilite'),
        ('index', '0015_alter_commande_reservation_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_permit', models.ImageField(blank=True, null=True, upload_to='permit/%y/%m/%d')),
                ('matricule', models.CharField(default='0000/0/00', max_length=10)),
                ('totalprix', models.CharField(default='0', max_length=10)),
                ('date_encharge', models.DateField(blank=True, null=True)),
                ('date_endepot', models.DateField(blank=True, null=True)),
                ('disponibilite', models.CharField(default='NON', max_length=5)),
                ('available', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.client')),
                ('voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.voiture')),
            ],
        ),
    ]
