# Generated by Django 5.0.4 on 2024-05-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_archivereservation_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivereservation',
            name='totalprix',
            field=models.IntegerField(),
        ),
    ]
